services:
  api:
    build:
      context: .
    restart: always
    # env_file:
    #   - .env
    ports:
      - 8000:8000
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  grpc_server:
    build:
      context: .
    restart: always
    depends_on:
      - api
    ports:
      - "50051:50051"
    command: [ "python", "manage.py", "run_grpc"]
